apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pitstop
    pitstop.service: auditlogservice
  name: auditlogservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pitstop
        pitstop.service: auditlogservice
    spec:
      containers:
      - env:
        - name: PITSTOP_ENVIRONMENT
          value: Production
        image: pitstop/auditlogservice:latest
        name: auditlogservice
      restartPolicy: Always

