apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: customermanagementapi
    system: pitstop
    version: "2.0"
  name: customermanagementapi-v2
  namespace: pitstop
spec:
  replicas: 1
  selector: null
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: customermanagementapi
        system: pitstop
        version: "2.0"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: pitstop/customermanagementapi:2.0
        imagePullPolicy: IfNotPresent
        name: customermanagementapi
        ports:
        - containerPort: 5100
        resources: {}
      restartPolicy: Always
status: {}
---
