apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: customermanagementapi-rule
  namespace: pitstop
spec:
  host: customermanagementapi
  subsets:
  - labels:
      version: v1
    name: version-v1
  - labels:
      version: v2
    name: version-v2

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customermanagementapi-vs
  namespace: pitstop
spec:
  hosts:
    - customermanagementapi
  http:
  - route:
    - destination:
        host: customermanagementapi
        subset: version-v1
      weight: 50
    - destination:
        host: customermanagementapi
        subset: version-v2
      weight: 50