apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pitstop
    pitstop.service: customermanagementapi
  name: customermanagementapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pitstop
        pitstop.service: customermanagementapi
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ApplicationInsights__InstrumentationKey
          value: befe2a5c-f406-4e9c-9a77-1dc88b331642
        image: pitstop/customermanagementapi:latest
        name: customermanagementapi
        ports:
        - containerPort: 5100
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: pitstop
    pitstop.service: customermanagementapi
  name: customermanagementapi
spec:
  type: NodePort
  ports:
  - name: "5100"
    port: 5100
    targetPort: 5100
    nodePort: 30005
  selector:
    app: pitstop
    pitstop.service: customermanagementapi
