apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: customermanagementapi
    version: v1
  name: customermanagementapi
  namespace: pitstop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        system: pitstop
        app: customermanagementapi
        version: v1
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ApplicationInsights__InstrumentationKey
          value: befe2a5c-f406-4e9c-9a77-1dc88b331642
        image: pitstop/customermanagementapi:latest
        name: customermanagementapi
        ports:
        - containerPort: 5100
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    system: pitstop
    app: customermanagementapi
    version: v1
  name: customermanagementapi
  namespace: pitstop
spec:
  type: NodePort
  ports:
  - name: "http-5100"
    port: 5100
    targetPort: 5100
    nodePort: 30005
  selector:
    system: pitstop
    app: customermanagementapi
    version: v1
