apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pitstop
    pitstop.service: logserver
  name: logserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pitstop
        pitstop.service: logserver
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        image: datalust/seq:latest
        name: logserver
        ports:
        - containerPort: 80
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: pitstop
    pitstop.service: logserver
  name: logserver
spec:
  type: NodePort
  ports:
  - name: "seq"
    port: 5341
    targetPort: 80
    nodePort: 30003
  selector:
    app: pitstop
    pitstop.service: logserver
