apiVersion: v1
kind: Service
metadata:
  labels:
    app: pitstop
    pitstop.service: logserver
  name: logserver
spec:
  type: NodePort
  ports:
  - name: "seq"
    port: 5341
    targetPort: 80
    nodePort: 30003
  selector:
    app: pitstop
    pitstop.service: logserver
status:
  loadBalancer: {}
