apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pitstop
    pitstop.service: mailserver
  name: mailserver
  namespace: pitstop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pitstop
        pitstop.service: mailserver
    spec:
      containers:
      - image: djfarrelly/maildev
        name: mailserver
        ports:
        - containerPort: 25
        - containerPort: 80
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: pitstop
    pitstop.service: mailserver
  name: mailserver
  namespace: pitstop
spec:
  type: NodePort
  ports:
  - name: "smtp"
    port: 25
    targetPort: 25
  - name: "web"
    port: 4000
    targetPort: 80
    nodePort: 30002
  selector:
    app: pitstop
    pitstop.service: mailserver
