apiVersion: v1
kind: Service
metadata:
  labels:
    app: pitstop
    pitstop.service: mailserver
  name: mailserver
spec:
  type: NodePort
  ports:
  - name: "smtp"
    port: 25
    targetPort: 25
  - name: "web"
    port: 4000
    targetPort: 80
    nodePort: 30002
  selector:
    app: pitstop
    pitstop.service: mailserver
status:
  loadBalancer: {}
