apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pitstop
    pitstop.service: notificationservice
  name: notificationservice
  namespace: pitstop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pitstop
        pitstop.service: notificationservice
    spec:
      containers:
      - env:
        - name: PITSTOP_ENVIRONMENT
          value: Production
        image: pitstop/notificationservice:latest
        name: notificationservice
      restartPolicy: Always
