apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pitstop
    pitstop.service: sqlserver
  name: sqlserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pitstop
        pitstop.service: sqlserver
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: Developer
        - name: SA_PASSWORD
          value: 8jkGh47hnDw89Haq8LN2
        image: microsoft/mssql-server-linux:latest
        name: sqlserver
        ports:
        - containerPort: 1433
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: pitstop
    pitstop.service: sqlserver
  name: sqlserver
spec:
  type: NodePort
  ports:
  - name: "tds"
    port: 1433
    targetPort: 1433
    nodePort: 30000
  selector:
    app: pitstop
    pitstop.service: sqlserver