apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pitstop
    pitstop.service: timeservice
  name: timeservice
  namespace: pitstop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pitstop
        pitstop.service: timeservice
    spec:
      containers:
      - env:
        - name: PITSTOP_ENVIRONMENT
          value: Production
        image: pitstop/timeservice:latest
        name: timeservice
      restartPolicy: Always
