apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pitstop
    pitstop.service: vehiclemanagementapi
  name: vehiclemanagementapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pitstop
        pitstop.service: vehiclemanagementapi
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ApplicationInsights__InstrumentationKey
          value: befe2a5c-f406-4e9c-9a77-1dc88b331642
        image: pitstop/vehiclemanagementapi:latest
        name: vehiclemanagementapi
        ports:
        - containerPort: 5000
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: pitstop
    pitstop.service: vehiclemanagementapi
  name: vehiclemanagementapi
spec:
  type: NodePort
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30006
  selector:
    app: pitstop
    pitstop.service: vehiclemanagementapi

