apiVersion: v1
kind: Service
metadata:
  labels:
    app: pitstop
    pitstop.service: vehiclemanagementapi
  name: vehiclemanagementapi
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    app: pitstop
    pitstop.service: vehiclemanagementapi
status:
  loadBalancer: {}
