apiVersion: v1
kind: Service
metadata:
  labels:
    app: pitstop
    pitstop.service: vehiclemanagementapi
  name: vehiclemanagementapi
spec:
  type: NodePort
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30006
  selector:
    app: pitstop
    pitstop.service: vehiclemanagementapi
status:
  loadBalancer: {}
