apiVersion: v1
kind: Service
metadata:
  labels:
    app: pitstop
    pitstop.service: workshopmanagementapi
  name: workshopmanagementapi
spec:
  ports:
  - name: "5200"
    port: 5200
    targetPort: 5200
  selector:
    app: pitstop
    pitstop.service: workshopmanagementapi
status:
  loadBalancer: {}
